### ISSUE TITLE
Publish to repository

### ISSUE THREAD

**Issue by michaelruocco** [yciabaud/jmeter-ssh-sampler#12]
Would it possible to get this code published into a repository such as maven central or jcenter? This would make it more easily usable as clients would not have to build and install it manually, instead it could be included as an entry in a maven pom file or gradle build script for example.

**Comment by yciabaud** [comment]
Hi Michael,

this plugin is integrated with https://jmeter-plugins.org which is some kind of standard way to install plugins in JMeter.

How would you use a maven dependency?

**Comment by michaelruocco** [comment]
Hi Yoann,

Thanks for the quick response, and please excuse my ignorance, I am not overly familiar with the details of JMeter, I have been asked to come in and help clean up the build process on an existing project that I am still getting up to speed on.

We have a use case where we are wanting to pull this code as dependency into a standard java project.

It has actually been worked on by a group of other guys so I am not sure exactly why. I have removed the dependency from their gradle.build file and the code still compiles, so I am not sure why it has been added, I will have to go back and ask. For now I will close this issue until I have spoken to them, if it is still a requirement I may come back and raise a new one.

Thanks,
