### ISSUE TITLE
Some process are hung while running SSH Sampler through jmeter commandline.

### ISSUE THREAD

**Issue by venki07h9** [yciabaud/jmeter-ssh-sampler#13]
In my jmx, I'm using 'SSH command' sampler - To make it working, I've copied the respective jar file in /lib/ext folder [i.e **jmeter-ssh-sampler-0.1.0.jar** ] also kept the **'jsch-0.1.50.jar'** file at '**jmeter/lib**' directory. When I'm running the jmx from command-line, encountered with below issue. _[Note: Jmx got executed and respective response is available at jtl. But, the process is still running with below info]_

**Here is the log:**
Writing log file to: /sdl06930/tperf/output/1512531557701/sequential/shell.log
Created the tree successfully using shell.jmx
Starting the test @ Wed Dec 06 22:15:56 PST 2017 (1512627356465)
Waiting for possible Shutdown/StopTestNow/Heapdump message on port 4445
Tidying up ... @ Wed Dec 06 22:16:40 PST 2017 (1512627400181)
... end of run
The JVM should have exitted but did not.
The following non-daemon threads are still running (DestroyJavaVM is OK):
Thread[Connect thread 10.25.16.80 session,5,main], stackTrace:java.net.SocketInputStream#socketRead0
java.net.SocketInputStream#socketRead at line:116
java.net.SocketInputStream#read at line:170
java.net.SocketInputStream#read at line:141
com.jcraft.jsch.IO#getByte at line:82
com.jcraft.jsch.Session#read at line:908
com.jcraft.jsch.Session#run at line:1378
java.lang.Thread#run at line:745

Thread[DestroyJavaVM,5,main], stackTrace:

**Here is the part of jmx used for SSH command sampler:**
```
      <hashTree>
        <org.apache.jmeter.protocol.ssh.sampler.SSHSampler guiclass="TestBeanGUI" testclass="org.apache.jmeter.protocol.ssh.sampler.SSHSampler" testname="SSH Command" enabled="true">
          <stringProp name="command">/usr/bin/sh /Venki/test.sh</stringProp>
          <stringProp name="hostname">10.25.25.25</stringProp>
          <stringProp name="password">PassWord</stringProp>
          <intProp name="port">22</intProp>
          <stringProp name="username">root</stringProp>
        </org.apache.jmeter.protocol.ssh.sampler.SSHSampler>
        <hashTree/>
```

Some-times the process are running for very long time, seems hours.
Why this was happening ? Can you please suggest me the solution.?

**Comment by yciabaud** [comment]
I have no clue, this plugin makes the bridge to use JSch, ty to use the latest version to see if it helps.
I am sorry I cannot help you more than that.
