### ISSUE TITLE
Kerberos input interrupte the process of run ssh command in Jmeter

### ISSUE THREAD

**Issue by anstarword** [yciabaud/jmeter-ssh-sampler#14]
Hi, 
I meet an issue when using SSH Command sampler.
I running Jmeter in Windows10, and send ssh command to Linux machine
Jmeter version is 3.2 r1790748, jsch-0.1.54.jar in lib, ApacheJMeter_ssh-1.1.1.jar in lib/ext

I Add only one SSH Command sampler in the Thread Group with Hostname, Port, Login User name/Password, and other fields use default value

After I click run, the Jmeter UI will be waiting there. I check the cmd.exe window which used to start jmeter.bat, there ask me for username and password. Like this:
Kerberos username [ayan]: snap
Kerberos password for snap:

I need input the username and password again (which already configured in the SSH sampler page), then, Jmeter is continued to execute the command (date) in the remote Linux server.

Why Jmeter ask me Kerberos username and password?
I already input them.
In such manual step stop me to integrate ssh command sampler into my jmeter scripts.

Can you help to verify?

**Comment by sapradhan** [comment]
I also faced this issue. I found these properties set in remote machine's 
`/etc/ssh/sshd_config`
```
GSSAPIAuthentication yes
GSSAPICleanupCredentials yes
```

[This post suggests turning those off](https://sqatech.wordpress.com/2014/04/08/run-jmeter-ssh-sampler-got-kerberos-username-prompt-in-command-line/). However in my case I had no control over the server. 

So I made changes to PreferredAuthentications as suggested [here](https://stackoverflow.com/a/43512959/1285431). This got rid of Kerberos prompts PR #21

**Comment by yciabaud** [comment]
Thank you for providing a solution for this, if someone needs GSSAPI authentication we may want to add it or make it configurable but I don't have this king of server available for test.
