### ISSUE TITLE
Non-GUI Mode not correctly handled

### ISSUE THREAD

**Issue by verhagen** [yciabaud/jmeter-ssh-sampler#2]
__Why__
When using __jmeter-ssh-sampler__ in [Non-GUI Mode (Command Line mode)](http://jmeter.apache.org/usermanual/get-started.html#non_gui) an exception is raised.

__Concrete__
This case is seen, when running JMeter on a headless (Linux) machine. Running JMeter as part of a Maven configuration (using the [`jmeter-maven-plugin`](https://github.com/jmeter-maven-plugin/jmeter-maven-plugin)), on a [Jenkins](https://jenkins-ci.org/) build server.

Jenkins Console shows how JMeter is started

	JMeter is called with the following command line arguments: -n -t /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FI2/workspace/src/test/jmeter/intake_v02.jmx 

_In the line above is shown that the argument `-n`, is used (non-gui mode)_

JMeter log (as seen  in the job Workspace directory: `ws/target/jmeter/logs/intake_v02.jmx.log`)	

_At the bottum is the line shown `ERROR - jmeter.JMeter: Uncaught exception:  java.awt.AWTError`. Which is caused, because [X11](https://en.wikipedia.org/wiki/X_Window_System) is not available._

	2015/10/16 09:27:08 INFO  - jmeter.util.JMeterUtils: Setting Locale to en 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: Loading user properties from: /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FI2/workspace/target/jmeter/bin/user.properties 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: Loading system properties from: /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FI2/workspace/target/jmeter/bin/system.properties 
	2015/10/16 09:27:08 WARN  - jmeter.JMeter: LogLevel: DEBUG 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: Copyright (c) 1998-2015 The Apache Software Foundation 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: Version 2.13 r1665067 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: java.version=1.8.0_60 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: java.vm.name=Java HotSpot(TM) 64-Bit Server VM 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: os.name=Linux 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: os.arch=amd64 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: os.version=3.10.0-229.7.2.el7.x86_64 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: file.encoding=UTF-8 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: Default Locale=English 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: JMeter  Locale=English 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: JMeterHome=/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FI2/workspace/target/jmeter 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: user.dir  =/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FI2/workspace/target/jmeter/bin 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: PWD       =/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FI2/workspace/target/jmeter/bin 
	2015/10/16 09:27:08 INFO  - jmeter.JMeter: IP: 172.17.0.1 Name: 4d14addf5da6 FullName: 4d14addf5da6 
	2015/10/16 09:27:08 INFO  - jmeter.services.FileServer: Default base='/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FI2/workspace/target/jmeter/bin' 
	2015/10/16 09:27:08 INFO  - jmeter.services.FileServer: Set new base='/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FI2/workspace/src/test/jmeter' 
	2015/10/16 09:27:09 INFO  - jmeter.save.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2 
	2015/10/16 09:27:09 INFO  - jmeter.save.SaveService: Using SaveService properties file encoding UTF-8 
	2015/10/16 09:27:09 INFO  - jmeter.save.SaveService: Using SaveService properties file version 1656252 
	2015/10/16 09:27:09 INFO  - jmeter.save.SaveService: Using SaveService properties version 2.8 
	2015/10/16 09:27:09 INFO  - jmeter.save.SaveService: All converter versions present and correct 
	2015/10/16 09:27:09 INFO  - jmeter.save.SaveService: Loading file: /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FI2/workspace/src/test/jmeter/intake_v02.jmx 
	2015/10/16 09:27:09 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Cannot find .className property for htmlParser, using default 
	2015/10/16 09:27:09 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/html is  
	2015/10/16 09:27:09 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xhtml+xml is  
	2015/10/16 09:27:09 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xml is  
	2015/10/16 09:27:09 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/xml is  
	2015/10/16 09:27:09 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser 
	2015/10/16 09:27:09 INFO  - jmeter.JMeter: Creating summariser <summary> 
	2015/10/16 09:27:09 INFO  - jmeter.engine.StandardJMeterEngine: Listeners will be started after enabling running version 
	2015/10/16 09:27:09 INFO  - jmeter.engine.StandardJMeterEngine: To revert to the earlier behaviour, define jmeterengine.startlistenerslater=false 
	2015/10/16 09:27:09 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
	2015/10/16 09:27:09 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
	2015/10/16 09:27:09 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
	2015/10/16 09:27:09 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must contain the string: '.functions.' 
	2015/10/16 09:27:09 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must not contain the string: '.gui.' 
	2015/10/16 09:27:09 ERROR - jmeter.JMeter: Uncaught exception:  java.awt.AWTError: Can't connect to X11 window server using ':99' as the value of the DISPLAY variable.
		at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)

**Comment by verhagen** [comment]
__Workaround__
There is a workaround, use the JVM option `-Djava.awt.headless=true`.

In `jmeter-maven-plugin` this can be done, by the following configuration, adding a `propertiesSystem`.

				<executions>
					<execution>
						<id>jmeter-tests</id>
						<phase>verify</phase>
						<goals>
							<goal>jmeter</goal>
						</goals>
						<configuration>
							<propertiesSystem>
								<java.awt.headless>true</java.awt.headless>
							</propertiesSystem>
						</configuration>
					</execution>
				</executions>

**Comment by yciabaud** [comment]
Thank you for reporting, can you provide a full stacktrace? 
I believe JSCH is referencing some awt classes... I used this plusgin in jenkins without any problem in the past, can you tell me if you are using ssh or sftp?

**Comment by verhagen** [comment]
We are using the SSH command, to execute a remote command.
(Full stacktrace, fill follow, on Monday)

**Comment by verhagen** [comment]
Here the complete logging as found in the `check.jmx.log`

	2015/10/22 06:57:23 INFO  - jmeter.util.JMeterUtils: Setting Locale to en 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Loading user properties from: /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin/user.properties 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Loading system properties from: /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin/system.properties 
	2015/10/22 06:57:23 WARN  - jmeter.JMeter: LogLevel: DEBUG 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Copyright (c) 1998-2015 The Apache Software Foundation 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Version 2.13 r1665067 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: java.version=1.8.0_60 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: java.vm.name=Java HotSpot(TM) 64-Bit Server VM 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: os.name=Linux 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: os.arch=amd64 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: os.version=3.10.0-229.7.2.el7.x86_64 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: file.encoding=UTF-8 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: Default Locale=English 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: JMeter  Locale=English 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: JMeterHome=/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: user.dir  =/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: PWD       =/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin 
	2015/10/22 06:57:23 INFO  - jmeter.JMeter: IP: 172.17.0.1 Name: 4d14addf5da6 FullName: 4d14addf5da6 
	2015/10/22 06:57:23 INFO  - jmeter.services.FileServer: Default base='/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/target/jmeter/bin' 
	2015/10/22 06:57:23 INFO  - jmeter.services.FileServer: Set new base='/var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/src/test/jmeter' 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Testplan (JMX) version: 2.2. Testlog (JTL) version: 2.2 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Using SaveService properties file encoding UTF-8 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Using SaveService properties file version 1656252 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Using SaveService properties version 2.8 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: All converter versions present and correct 
	2015/10/22 06:57:23 INFO  - jmeter.save.SaveService: Loading file: /var/jenkins_home/jobs/jmeter-environment-health-check_develop_FIT-tmp/workspace/src/test/jmeter/intake_v02.jmx 
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Cannot find .className property for htmlParser, using default 
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/html is  
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xhtml+xml is  
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for application/xml is  
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/xml is  
	2015/10/22 06:57:23 INFO  - jmeter.protocol.http.sampler.HTTPSamplerBase: Parser for text/vnd.wap.wml is org.apache.jmeter.protocol.http.parser.RegexpHTMLParser 
	2015/10/22 06:57:24 INFO  - jmeter.JMeter: Creating summariser <summary> 
	2015/10/22 06:57:24 INFO  - jmeter.engine.StandardJMeterEngine: Listeners will be started after enabling running version 
	2015/10/22 06:57:24 INFO  - jmeter.engine.StandardJMeterEngine: To revert to the earlier behaviour, define jmeterengine.startlistenerslater=false 
	2015/10/22 06:57:24 INFO  - jmeter.engine.StandardJMeterEngine: Running the test! 
	2015/10/22 06:57:24 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
	2015/10/22 06:57:24 INFO  - jmeter.samplers.SampleEvent: List of sample_variables: [] 
	2015/10/22 06:57:24 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must contain the string: '.functions.' 
	2015/10/22 06:57:24 INFO  - jmeter.engine.util.CompoundVariable: Note: Function class names must not contain the string: '.gui.' 
	2015/10/22 06:57:24 ERROR - jmeter.JMeter: Uncaught exception:  java.awt.AWTError: Can't connect to X11 window server using ':99' as the value of the DISPLAY variable.
		at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
		at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
		at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
		at java.security.AccessController.doPrivileged(Native Method)
		at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
		at java.lang.Class.forName0(Native Method)
		at java.lang.Class.forName(Class.java:264)
		at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
		at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
		at java.awt.Window.initGC(Window.java:475)
		at java.awt.Window.init(Window.java:495)
		at java.awt.Window.<init>(Window.java:537)
		at java.awt.Frame.<init>(Frame.java:420)
		at java.awt.Frame.<init>(Frame.java:385)
		at com.ibm.as400.access.ToolboxSignonHandler.displayMessage(ToolboxSignonHandler.java:336)
		at com.ibm.as400.access.ToolboxSignonHandler.displayMessage(ToolboxSignonHandler.java:323)
		at com.ibm.as400.access.ToolboxSignonHandler.userIdDisabled(ToolboxSignonHandler.java:248)
		at com.ibm.as400.access.AS400.promptSignon(AS400.java:2824)
		at com.ibm.as400.access.AS400.signon(AS400.java:4076)
		at com.ibm.as400.access.AS400.connectService(AS400.java:1203)
		at com.ibm.as400.access.AS400JDBCConnection.setProperties(AS400JDBCConnection.java:3342)
		at com.ibm.as400.access.AS400JDBCDriver.prepareConnection(AS400JDBCDriver.java:1419)
		at com.ibm.as400.access.AS400JDBCDriver.initializeConnection(AS400JDBCDriver.java:1256)
		at com.ibm.as400.access.AS400JDBCDriver.connect(AS400JDBCDriver.java:395)
		at java.sql.DriverManager.getConnection(DriverManager.java:664)
		at java.sql.DriverManager.getConnection(DriverManager.java:247)
		at org.apache.avalon.excalibur.datasource.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:142)
		at org.apache.avalon.excalibur.datasource.ResourceLimitingJdbcDataSource.configure(ResourceLimitingJdbcDataSource.java:311)
		at org.apache.jmeter.protocol.jdbc.config.DataSourceElement.initPool(DataSourceElement.java:235)
		at org.apache.jmeter.protocol.jdbc.config.DataSourceElement.testStarted(DataSourceElement.java:108)
		at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:214)
		at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:336)
		at java.lang.Thread.run(Thread.java:745)

	2015/10/22 06:57:24 INFO  - jmeter.reporters.ResultCollector: Shutdown hook started 
	2015/10/22 06:57:24 INFO  - jmeter.reporters.ResultCollector: Shutdown hook ended

**Comment by yciabaud** [comment]
Closing since this does not look like its related to this plugin. The sql driver seems to output an error dialog in the gui.  Setting `-Djava.awt.headless=true` must be the way to go.
