### ISSUE TITLE
Rename doesn't work

### ISSUE THREAD

**Issue by alvmarveg** [yciabaud/jmeter-ssh-sampler#24]
**Easy changes:**

This line is wrong
[SSHSFTPSampler.java](https://github.com/yciabaud/jmeter-ssh-sampler/blob/master/src/main/java/org/apache/jmeter/protocol/ssh/sampler/SSHSFTPSampler.java#L46)

This line is missing the rename action
[SSHSFTPSamplerBeanInfo.java](https://github.com/yciabaud/jmeter-ssh-sampler/blob/master/src/main/java/org/apache/jmeter/protocol/ssh/sampler/SSHSFTPSamplerBeanInfo.java#L45)

**Comment by yciabaud** [comment]
Issue is solved now tanks to @antoniochiurla
