### ISSUE TITLE
Thread still running due to socket

### ISSUE THREAD

**Issue by Buzz2Buzz** [yciabaud/jmeter-ssh-sampler#3]
Hello,

Is it possible to configure a timeout with the SSH Sampler ?
I'm facing a strange issue when using Jmeter with Jenkins.

```
The JVM should have exitted but did not.
The following non-daemon threads are still running (DestroyJavaVM is OK):
Thread[DestroyJavaVM,5,main], stackTrace:
Thread[Connect thread 192.168.70.197 session,5,main], stackTrace:java.net.SocketInputStream#socketRead0
java.net.SocketInputStream#socketRead at line:116
java.net.SocketInputStream#read at line:170
java.net.SocketInputStream#read at line:141
com.jcraft.jsch.IO#getByte at line:82
com.jcraft.jsch.Session#read at line:918
com.jcraft.jsch.Session#run at line:1392
java.lang.Thread#run at line:745
```

I Googled it but none contained 
```
com.jcraft.jsch.IO#getByte at line:82
com.jcraft.jsch.Session#read at line:918
com.jcraft.jsch.Session#run at line:1392
```

And it seems that only the SSH Sampler can produce that stack, right ?

The real problem is that when I'm debugging locally, it works well. With jenkins on the other machine I get that after all the tests passed.

**Comment by Buzz2Buzz** [comment]
All apologies, the whole thing was a wrong version... Last in date is OK

**Comment by yciabaud** [comment]
Good to hear it.
Thank you for letting me know
