### ISSUE TITLE
On jmeter maven, "mvn verify" instructions...

### ISSUE THREAD

**Issue by sdfnanderson** [yciabaud/jmeter-ssh-sampler#4]
Hello, greetings from Brazil.

About the instructions :
-------------------------------------------------------------------------------------------
About: v1.1.0 

@yciabaud yciabaud released this Feb 12, 2014 ·  1 commit to master since this release 

•Copy the ApacheJMeter_ssh-1.1.0.jar to $JMETER_HOME/lib/ext directory
•Copy the jsch-0.1.51.jar to $JMETER_HOME/lib directory if needed
------------------------------------------------------------------------------------------
About The issue:
how to run ssh shell test on maven jmeter as a dependency? Can you add one "for dummies" example in the main page, like "insert the dependency in maven mvn verify project..."?

partial mvn verify jmeter failed automated script, with profile, etc....
....
 <profile>
            <id>integrated</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>com.lazerycode.jmeter</groupId>
                        <artifactId>jmeter-maven-plugin</artifactId>
                        <version>1.10.1</version>
                        <executions>
                            <execution>
                                <id>jmeter-tests</id>
                                <phase>verify</phase>
                                <goals>
                                    <goal>jmeter</goal>
                                </goals>
                                <configuration>
                                    <suppressJMeterOutput>false</suppressJMeterOutput>
                                    <overrideRootLogLevel>debug</overrideRootLogLevel>
                                    <proxyConfig>
                                        <host>xx</host>
                                        <port>6060</port>
                                        <username>xpto</username>
                                        <password>acme</password>
                                        <hostExclusions>10.5.112.126</hostExclusions>
                                    </proxyConfig>
                                    <propertiesUser> 
                                        <EXECUTE_CORE>false</EXECUTE_CORE>
                                       <EXECUTE_INTEGRATED>true</EXECUTE_INTEGRATED>
                                    </propertiesUser> 
                                </configuration>
                            </execution>
                        </executions>
                        <dependencies> 
                            
                            <dependency>
                                <groupId>org.postgresql</groupId>
                                <artifactId>postgresql</artifactId>
                                <version>9.4-1200-jdbc41</version>
                            </dependency>
                         
----------------------------------------------------------------------------------------
   <dependency>  
                                <groupId>org.apache.jmeter.protocol.ssh.sampler.SSHCommandSampler</groupId>
                               <artifactId>org.apache.jmeter.protocol.ssh.sampler.SSHCommandSampler</artifactId>
                                <version>1.1.0</version>
                            </dependency>
-------------------------------------------------------------------------------------------------
                        </dependencies>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

**Comment by yciabaud** [comment]
Hello from France!

I am sorry but I don't understand quite well your issue.

Running JMeter with SSH plugin with maven is not different from running it with another plugin.

Try the maven jmeter documentation: https://github.com/jmeter-maven-plugin/jmeter-maven-plugin/wiki/Adding%20Additional%20Libraries%20To%20The%20Classpath

You will need to add this plugin to your maven repository before.

**Comment by yciabaud** [comment]
Closing since I don't have enough informations.
