### ISSUE TITLE
SSH connexion error com.jcraft.jsch.JSchException: java.net.ConnectException: Connection refused

### ISSUE THREAD

**Issue by innocentliny** [yciabaud/jmeter-ssh-sampler#5]
Hi,

I'm using below in CentOS 7:
JMeter 3.0 r1743807
jmeter-ssh-sampler v1.1.1-SNAPSHOT
jsch-0.1.53.jar

I have a SFTP server with Apache SSHD v1.2.0 + Wireshark + Windows 7.
> When I test 100 Threads + Loop 1, I get below error for some threads:
> 
> 2016/09/02 11:42:48 ERROR - jmeter.protocol.ssh.sampler.AbstractSSHSampler: SSH connexion error com.jcraft.jsch.JSchException: java.net.ConnectException: Connection refused
> 	at com.jcraft.jsch.Util.createSocket(Util.java:394)
> 	at com.jcraft.jsch.Session.connect(Session.java:215)
> 	at org.apache.jmeter.protocol.ssh.sampler.AbstractSSHSampler.connect(AbstractSSHSampler.java:72)
> 	at org.apache.jmeter.protocol.ssh.sampler.SSHSFTPSampler.sample(SSHSFTPSampler.java:73)
> 	at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:465)
> 	at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:410)
> 	at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:241)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.net.ConnectException: Connection refused
> 	at java.net.PlainSocketImpl.socketConnect(Native Method)
> 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
> 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
> 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
> 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
> 	at java.net.Socket.connect(Socket.java:589)
> 	at java.net.Socket.connect(Socket.java:538)
> 	at java.net.Socket.<init>(Socket.java:434)
> 	at java.net.Socket.<init>(Socket.java:211)
> 	at com.jcraft.jsch.Util$1.run(Util.java:362)
> 	... 1 more

I noticed that Wireshark (at server side) didn't get any packets from the refused connection, and it means the thread didn't really connect to server and thought its connection was refused, but it's not true.
And when I test 50 threads + Loop 100, everything is fine, no connection is refused.
I have no idea why this happened.

Does anyone have any comments?
Thank you.

**Comment by yciabaud** [comment]
Hello, you have probably reached a limit on the server. Have a look at your firewall, your os socket limits or your sshd configuration.

**Comment by innocentliny** [comment]
Hi, yciabaud:

I think you're right. Thanks for the hint.
