### ISSUE TITLE
Question: How to pass ssh client options?

### ISSUE THREAD

**Issue by Twoflower2** [yciabaud/jmeter-ssh-sampler#8]
Hi,
how do I pass ssh/sftp client options using the jmeter GUI:

 -o option
             Can be used to give options in the format used in the
             configuration file.  This is useful for specifying options for
             which there is no separate command-line flag.  For full details
             of the options listed below, and their possible values, see
             ssh_config(5).

                   AddKeysToAgent
                   AddressFamily
                   BatchMode
                   BindAddress
                   CanonicalDomains
                   CanonicalizeFallbackLocal
                   CanonicalizeHostname
                   CanonicalizeMaxDots
                   CanonicalizePermittedCNAMEs
                   CertificateFile
                   ChallengeResponseAuthentication
                   CheckHostIP
                   Cipher
                   Ciphers
                   ClearAllForwardings
                   Compression
                   CompressionLevel
                   ConnectionAttempts
                   ConnectTimeout
                   ControlMaster
                   ControlPath
                   ControlPersist
                   DynamicForward
                   EscapeChar
                   ExitOnForwardFailure
                   FingerprintHash
                   ForwardAgent
                   ForwardX11
                   ForwardX11Timeout
                   ForwardX11Trusted
                   GatewayPorts
                   GlobalKnownHostsFile
                   GSSAPIAuthentication
                   GSSAPIDelegateCredentials
                   HashKnownHosts
                   Host
                   HostbasedAuthentication
                   HostbasedKeyTypes
                   HostKeyAlgorithms
                   HostKeyAlias
                   HostName
                   IdentityFile
                   IdentitiesOnly
                   IPQoS
                   KbdInteractiveAuthentication
                   KbdInteractiveDevices
                   KexAlgorithms
                   LocalCommand
                   LocalForward
                   LogLevel
                   MACs
                   Match
                   NoHostAuthenticationForLocalhost
                   NumberOfPasswordPrompts
                   PasswordAuthentication
                   PermitLocalCommand
                   PKCS11Provider
                   Port
                   PreferredAuthentications
                   Protocol
                   ProxyCommand
                   ProxyUseFdpass
                   PubkeyAcceptedKeyTypes
                   PubkeyAuthentication
                   RekeyLimit
                   RemoteForward
                   RequestTTY
                   RhostsRSAAuthentication
                   RSAAuthentication
                   SendEnv
                   ServerAliveInterval
                   ServerAliveCountMax
                   StreamLocalBindMask
                   StreamLocalBindUnlink
                   StrictHostKeyChecking
                   TCPKeepAlive
                   Tunnel
                   TunnelDevice
                   UpdateHostKeys
                   UsePrivilegedPort
                   User
                   UserKnownHostsFile
                   VerifyHostKeyDNS
                   VersionAddendum
                   VisualHostKey
                   XAuthLocation

**Comment by yciabaud** [comment]
Sorry man I don't remember I have been notified about these messages, I know it is too late but I will answer in case of some other user needs to know the answer.

This plugin uses JSch to handle SSH protocol, it does not implement all these options but it does implement this: http://epaul.github.io/jsch-documentation/simple.javadoc/com/jcraft/jsch/JSch.html#setConfig-java.lang.String-java.lang.String-

We could implement these options by adding a component or by using a variable prefix, if anyone interested, we could set a PR up on this purpose.

**Comment by Twoflower2** [comment]
@yciabaud These options should be quite easy to use from this plugin. On the cmd line it is used like this for example: 
for port option: `sftp -oPort=22333 user@host`
for cipher option: `sftp -oCiphers=aes128-ctr user@host`

All that is needed is for a place in the plugin UI to enter options and then it should be added to the sftp/ssh cmd by the plugin logic. No parsing is even necessary in the logic really. The client does do some checking itself and will fail the connection if the options are incorrect.
